# Generated by Django 3.0.5 on 2020-05-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alekhya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='phonenumber',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
